# Seminar_1 

Exercise 1

In [2]:
class RGBto_YUV:
    def YUV_to_RGB(Y, U,V):
        B = round(1.163 * (Y -16) + 2.018 * (U - 128))
        G = round(1.164 * (Y - 16) - 0.813 * (V - 128) - 0.391 * (U - 128))
        R = round(1.164 * (Y - 16) + 1.596 * (V - 128)) 
        return(R, G, B)
    
    def RGB_to_YUV(R,G,B):
        Y = round(0.257 * R + 0.504 * G + 0.098 * B +16)
        U = round(-0.148 * R - 0.291 * G + 0.439 * B +128)
        V = round(0.439 * R - 0.368 * G - 0.071 * B +128)
        return(Y,U,V)
        

In [3]:
Y, U, V = 100, 128, 128

# Convertir YUV a RGB
R, G, B = RGBto_YUV.YUV_to_RGB(Y, U, V)
print(f"Valores RGB: R = {R}, G = {G}, B = {B}")

Valores RGB: R = 98, G = 98, B = 98


In [4]:
# Convertir RGB a YUV
Y, U, V = RGBto_YUV.RGB_to_YUV(R, G, B)
print(f"Valores YUV: Y = {Y}, U = {U}, V = {V}")

Valores YUV: Y = 100, U = 128, V = 128


Exercise 2

In [5]:
import subprocess

input_image = "/Users/viktoriaolmedo/Downloads/escut-barca.png"
output_image = "/Users/viktoriaolmedo/Downloads/resized_image.png"

#modificar per path de cada ordinador


def resize_image(input_image, output_image, width, height, quality = 28):

    command = ["ffmpeg","-y","-loglevel", "info","-i", input_image,"-vf", f"scale={width}:{height}",output_image ]

    try:
        result = subprocess.run(command, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        print(result.stdout)
        print(f"Resized image saved to {output_image}")
    except subprocess.CalledProcessError as e:
        print("Error ocurred while running FFmpeg", e.stderr)


#ffmpeg -i input.jpg -vf scale=320:240 output_320x240.png

resize_image(input_image, output_image, 320, 240, quality=28)

Error ocurred while running FFmpeg ffmpeg version 2024-09-26-git-f43916e217-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libopenjpeg --enable-libquirc --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-libqrencode --enable-librav1e --enable-libsvtav1 --enable-libvvenc --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libvpx --enable-mediafoun

Exercise 3

In [40]:
import numpy as np

# Crear la matriz 8x8 llena con los valores del 1 al 64
matrix = np.arange(1, 65).reshape(8, 8)

# Función para recorrer la matriz en zig-zag de acuerdo a la descripción
def zigzag_traversal(matrix):
    result = [None] * 64
    n = matrix.shape[0]  # Tamaño de la matriz (8x8)
    a = 0
    result[a] = matrix[0][0] #First value
    i = 0
    j = 0
    while (a < 63):        
        #step 1: (one to the right)
        a += 1
        pos_i = i + 1
        pos_j = j + 0
        result[a] = matrix[pos_i][pos_j]
        
        
        #step 2: (Diagonal down to the left until reaching the wall)
        while(pos_i != 0):
            a += 1
            pos_i += - 1
            pos_j += + 1
            result[a] = matrix[pos_i][pos_j]
        
        #step 3: (one down) 
        a += 1
        pos_j += + 1
        result[a] = matrix[pos_i][pos_j]
        
        #step 4:
        while(pos_j != 0):
            a += 1
            pos_i += + 1
            pos_j += - 1
            result[a] = matrix[pos_i][pos_j]
            
    return result


# Obtener el recorrido zig-zag
zigzag_result = zigzag_traversal(matrix)

# Mostrar la matriz y el recorrido zig-zag
print("Matriz 8x8:")
print(matrix)
print("\nRecorrido Zig-Zag:")
print(zigzag_result)


IndexError: list assignment index out of range

In [ ]:
import numpy as np

matrix = np.arange(1, 65).reshape(8, 8)

def zigzag_traversal(matrix):
    result = [None] * 64  
    n = matrix.shape[0]  # Tamaño de la matriz (8x8)
    
    a = 0  
    i = 0  
    j = 0  
    result[a] = matrix[i][j]  # First value
    
    while a < 63:  
        #step 1: (one to the right)
        if j + 1 < n:  
            j += 1
            a += 1
            result[a] = matrix[i][j]
        
        #step 2: (Diagonal down to the left until reaching the wall)
        while i + 1 < n and j - 1 >= 0:  # Verificar que no se salga de la matriz
            i += 1
            j -= 1
            a += 1
            if a < 64:  # Verificar que no se salga de la lista
                result[a] = matrix[i][j]
        
        #step 3: (one down) 
        if i + 1 < n:  # Verificar que no se salga de la matriz
            i += 1
            a += 1
            if a < 64:  # Verificar que no se salga de la lista
                result[a] = matrix[i][j]
        
        #step 4: (Diagonal up to the right until reaching the top)
        while j + 1 < n and i - 1 >= 0:  
            i -= 1
            j += 1
            a += 1
            if a < 64:  
                result[a] = matrix[i][j]
        if a >= 63:
            break
    
    return result

zigzag_result = zigzag_traversal(matrix)

# Mostrar la matriz y el recorrido zig-zag
print("Matriz 8x8:")
print(matrix)
print("\nRecorrido Zig-Zag:")
print(zigzag_result)


Matriz 8x8:
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]

Recorrido Zig-Zag:
[1, 2, 9, 17, 10, 3, 4, 11, 18, 25, 33, 26, 19, 12, 5, 6, 13, 20, 27, 34, 41, 49, 42, 35, 28, 21, 14, 7, 8, 15, 22, 29, 36, 43, 50, 57, 50, 43, 36, 29, 22, 15, 8, 15, 22, 29, 36, 43, 50, 57, 50, 43, 36, 29, 22, 15, 8, 15, 22, 29, 36, 43, 50, 57]
