# Seminar_1 

**Exercise 1**

In [28]:
class RGBto_YUV:
    def YUV_to_RGB(Y, U,V):
        B = round(1.163 * (Y -16) + 2.018 * (U - 128))
        G = round(1.164 * (Y - 16) - 0.813 * (V - 128) - 0.391 * (U - 128))
        R = round(1.164 * (Y - 16) + 1.596 * (V - 128)) 
        return(R, G, B)
    
    def RGB_to_YUV(R,G,B):
        Y = round(0.257 * R + 0.504 * G + 0.098 * B +16)
        U = round(-0.148 * R - 0.291 * G + 0.439 * B +128)
        V = round(0.439 * R - 0.368 * G - 0.071 * B +128)
        return(Y,U,V)
        

In [29]:
Y, U, V = 100, 128, 128

# Convertir YUV a RGB
R, G, B = RGBto_YUV.YUV_to_RGB(Y, U, V)
print(f"Valores RGB: R = {R}, G = {G}, B = {B}")

Valores RGB: R = 98, G = 98, B = 98


In [30]:
# Convertir RGB a YUV
Y, U, V = RGBto_YUV.RGB_to_YUV(R, G, B)
print(f"Valores YUV: Y = {Y}, U = {U}, V = {V}")

Valores YUV: Y = 100, U = 128, V = 128


**Exercise 2**

In [31]:
import subprocess

input_image = "/Users/viktoriaolmedo/Downloads/escut-barca.png"
output_image = "/Users/viktoriaolmedo/Downloads/resized_image.png"

#modificar per path de cada ordinador


def resize_image(input_image, output_image, width, height, quality = 28):

    command = ["ffmpeg","-y","-loglevel", "info","-i", input_image,"-vf", f"scale={width}:{height}",output_image ]

    try:
        result = subprocess.run(command, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        print(result.stdout)
        print(f"Resized image saved to {output_image}")
    except subprocess.CalledProcessError as e:
        print("Error ocurred while running FFmpeg", e.stderr)


#ffmpeg -i input.jpg -vf scale=320:240 output_320x240.png

resize_image(input_image, output_image, 320, 240, quality=28)

Error ocurred while running FFmpeg ffmpeg version 2024-09-26-git-f43916e217-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libopenjpeg --enable-libquirc --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-libqrencode --enable-librav1e --enable-libsvtav1 --enable-libvvenc --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libvpx --enable-mediafoun

**Exercise 3**

We first implement it with a matrix 8x8 in order to check if the algorithm is really working. 

In [32]:
import numpy as np

matrix = np.arange(1, 65).reshape(8, 8)

def zigzag_traversal(matrix):
    result = [None] * 64  
    n = matrix.shape[0]  
    
    a = 0  
    i = 0 
    j = 0 
    result[a] = matrix[i][j]  # First value
    
    while a < 63:  
        #step 1: (one to the right)
        if j == n - 1:  
            i += 1
        else:
            j += 1

        a += 1
        if a < 64:
            result[a] = matrix[i][j]
        
        #step 2: (Diagonal down to the left until reaching j = 0)
        while i + 1 < n and j - 1 >= 0 and a < 63:
            i += 1
            j -= 1
            a += 1
            result[a] = matrix[i][j]
        
        #step 3: (one down) 
        if i == n - 1:  
            j += 1
        else:
            i += 1

        a += 1
        if a < 64:
            result[a] = matrix[i][j]
        
        #step 4: (Diagonal up to the right until reaching i = 0)
        while j + 1 < n and i - 1 >= 0 and a < 63:
            i -= 1
            j += 1
            a += 1
            result[a] = matrix[i][j]
    
    return result

# Obtener el recorrido zig-zag
zigzag_result = zigzag_traversal(matrix)

# Mostrar la matriz y el recorrido zig-zag
print("Matriz 8x8:")
print(matrix)
print("\nRecorrido Zig-Zag:")
print(zigzag_result)


Matriz 8x8:
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]

Recorrido Zig-Zag:
[1, 2, 9, 17, 10, 3, 4, 11, 18, 25, 33, 26, 19, 12, 5, 6, 13, 20, 27, 34, 41, 49, 42, 35, 28, 21, 14, 7, 8, 15, 22, 29, 36, 43, 50, 57, 58, 51, 44, 37, 30, 23, 16, 24, 31, 38, 45, 52, 59, 60, 53, 46, 39, 32, 40, 47, 54, 61, 62, 55, 48, 56, 63, 64]


Then we implemented for images. We use the resize_image function generated in the previous exercise in order to obtain a nxn image. Then we implement the zig zag function and obtain the expected output (in Black and White because it was simpler to implement and was not giving us any problem compared to the RGB case). 

We can try and change the values of the resize image. In order to check if the algorithm is still working for this case with images, we have set the values to 16, because then we can see the complete matrix. But we could also do it for other values and the result would still be correct. 

In [41]:
import numpy as np
import cv2
import subprocess

def load_image(image_path):
    return cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)  

def serpentine(matrix):
    n = matrix.shape[0]  
    result = [None] * (n * n)  
    
    a = 0  
    i = 0 
    j = 0 
    result[a] = matrix[i, j]  # First value
    
    while a < n * n - 1:  
        #step 1: (one to the right)
        if j == n - 1:  
            i += 1
        else:
            j += 1

        a += 1
        if a < n * n:
            result[a] = matrix[i, j]
        
        #step 2: (Diagonal down to the left until reaching j = 0)
        while i + 1 < n and j - 1 >= 0 and a < n * n - 1:
            i += 1
            j -= 1
            a += 1
            result[a] = matrix[i, j]
        
        #step 3: (one down)
        if i == n - 1:  
            j += 1
        else:
            i += 1

        a += 1
        if a < n * n:
            result[a] = matrix[i, j]
        
        #step 4: (Diagonal up to the right until reaching i = 0)
        while j + 1 < n and i - 1 >= 0 and a < n * n - 1:
            i -= 1
            j += 1
            a += 1
            result[a] = matrix[i, j]
    
    return result

def serpentine_color(image):
    
    channels = cv2.split(image)
    serpentine_results_color = []
    
    for channel in channels:
        serpentine_results_color.append(zigzag_traversal(channel))
    
    return serpentine_results_color



# Inputs and Outputs
image = "/Users/isall/OneDrive/UNI/4_uni/1_trim_4/Audio/video_coding/first_seminar/logo_fcb.jpeg"
input_image = "/Users/isall/OneDrive/UNI/4_uni/1_trim_4/Audio/video_coding/first_seminar/logo_fcb_resize.jpeg"
resize_image(image, input_image, 16, 16, quality=28)
output_image = "/Users/isall/OneDrive/UNI/4_uni/1_trim_4/Audio/video_coding/first_seminar/zig_zag.jpeg"


#We load the resize image in BW
image_matrix = load_image(input_image)

if image_matrix is None:
    print("Error loading the image")
else:
    # Print the matrix to then check it the convertion is done well. 
    print("Original Matrix in Black and White:")
    print(image_matrix)


# Check if it's a nxn matrix
if image_matrix is None:
    print("Error loading the image")
else:
    assert image_matrix.shape[0] == image_matrix.shape[1], "The resize image is not nxn."

    serpentine_result = serpentine(image_matrix)

    print("Serpentine of image:")
    print(serpentine_result)

    n = image_matrix.shape[0]
    serpentine_image = np.array(serpentine_result).reshape((n, n))

    # Safe the output
    cv2.imwrite(output_image, serpentine_image)
    print(f"Output safe in: {output_image}")


Resized image saved to /Users/isall/OneDrive/UNI/4_uni/1_trim_4/Audio/video_coding/first_seminar/logo_fcb_resize.jpeg
Original Matrix in Black and White:
[[215 216 217 216 197 194 156 191 187 158 198 198 216 218 219 215]
 [215 217 212 214 130 138 110 131 127 128 125 139 215 216 216 215]
 [216 214 218 214 162 229 107 217 150 140 141 156 219 221 216 216]
 [220 218 216 219 170 129  84 131 141 141 137 172 221 216 219 216]
 [214 215 216 222 166  81  68  86 138 143 131 173 220 215 215 216]
 [217 213 217 215 173 206 100 215 152 140 137 171 218 219 215 218]
 [213 215 216 213 153 195 118 171 133 133 145 155 210 215 218 215]
 [211 219 220 190 157 190 147 125 121 132 202 157 189 219 218 216]
 [217 216 214 196 139 133 120 109  94 111 133 140 197 217 216 216]
 [215 217 220 215 107  52  53  70  74  58  51 109 215 215 217 215]
 [209 219 216 211 120  56  57 135 143  55  59 122 214 220 216 215]
 [218 212 216 218 139  59  55 145 145  58  56 147 226 213 215 218]
 [216 221 214 218 176  81  53 105 107  52

**Exercise 4**